map <F7> :tabp <CR>
map <F8> :tabn <CR>
map <F9> :tabe 
:set nu
:set expandtab
:set tabstop=4
" If the current buffer has never been saved, it will have no name,
" call the file browser to save it, otherwise just save it.
command -nargs=0 -bar Update if &modified
                           \|    if empty(bufname('%'))
                           \|        browse confirm write
                           \|    else
                           \|        confirm write
                           \|    endif
                           \|endif
:inoremap <c-s> <c-o>:Update<CR>
:highlight ExtraWhitespace ctermbg=red guibg=red
:match ExtraWhitespace /\s\+$/
