map <F7> :tabp <CR>
map <F8> :tabn <CR>
map <F6> :tabfind 
" set path+=** Put different path in folder specific .vimrc
set wildmenu
:set nu
:set expandtab
:set tabstop=4
" If the current buffer has never been saved, it will have no name,
" call the file browser to save it, otherwise just save it.
command -nargs=0 -bar Update if &modified
                           \|    if empty(bufname('%'))
                           \|        browse confirm write
                           \|    else
                           \|        confirm write
                           \|    endif
                           \|endif
:inoremap <c-s> <c-o>:Update<CR>
:highlight ExtraWhitespace ctermbg=red guibg=red
:match ExtraWhitespace /\s\+$/
:set foldmethod=indent
:set sw=4

" Install vim-plug if we don't already have it
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'https://github.com/leafgarland/typescript-vim.git'
Plug 'https://gitlab.com/code-stats/code-stats-vim.git'

" Optional: If you want a nice status line in Vim
Plug 'vim-airline/vim-airline'

call plug#end()
"type :PlugInstall to update
set exrc

let g:codestats_api_key = 'SFMyNTY.Wkc5dFpXNXBZMjg9IyNOamd5Tnc9PQ.7WVOrIV4XJlUk1Cb88mXGdXePJehjZoknvnzvaf2Tw0'
let g:airline_section_x = airline#section#create_right(['tagbar', 'filetype', '%{CodeStatsXp()}'])
